config/routes.rb
SystemStatus::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :outage_types

  resources :status_reports

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  root to: 'static_pages#home'

end

app/controllers/outage_types_controller.rb
class OutageTypesController < ApplicationController
  # GET /outage_types
  # GET /outage_types.json
  def index
    @outage_types = OutageType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @outage_types }
    end
  end

  # GET /outage_types/1
  # GET /outage_types/1.json
  def show
    @outage_type = OutageType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @outage_type }
    end
  end

  # GET /outage_types/new
  # GET /outage_types/new.json
  def new
    @outage_type = OutageType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @outage_type }
    end
  end

  # GET /outage_types/1/edit
  def edit
    @outage_type = OutageType.find(params[:id])
  end

  # POST /outage_types
  # POST /outage_types.json
  def create
    @outage_type = OutageType.new(params[:outage_type])

    respond_to do |format|
      if @outage_type.save
        format.html { redirect_to @outage_type, :notice => 'Outage type was successfully created.' }
        format.json { render :json => @outage_type, :status => :created, :location => @outage_type }
      else
        format.html { render :action => "new" }
        format.json { render :json => @outage_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /outage_types/1
  # PUT /outage_types/1.json
  def update
    @outage_type = OutageType.find(params[:id])

    respond_to do |format|
      if @outage_type.update_attributes(params[:outage_type])
        format.html { redirect_to @outage_type, :notice => 'Outage type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @outage_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /outage_types/1
  # DELETE /outage_types/1.json
  def destroy
    @outage_type = OutageType.find(params[:id])
    @outage_type.destroy

    respond_to do |format|
      format.html { redirect_to outage_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/outage_types_helper.rb
module OutageTypesHelper
end

app/views/outage_types/_form.html.erb
<%= form_for(@outage_type) do |f| %>
  <% if @outage_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outage_type.errors.count, "error") %> prohibited this outage_type from being saved:</h2>

      <ul>
      <% @outage_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.number_field :code %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outage_types/edit.html.erb
<h1>Editing outage_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @outage_type %> |
<%= link_to 'Back', outage_types_path %>

app/views/outage_types/index.html.erb
<h1>Listing outage_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Code</th>
    <th>Description</th>
    <th>Active</th>
    <th>Created by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @outage_types.each do |outage_type| %>
  <tr>
    <td><%= outage_type.name %></td>
    <td><%= outage_type.code %></td>
    <td><%= outage_type.description %></td>
    <td><%= outage_type.active %></td>
    <td><%= outage_type.created_by %></td>
    <td><%= link_to 'Show', outage_type %></td>
    <td><%= link_to 'Edit', edit_outage_type_path(outage_type) %></td>
    <td><%= link_to 'Destroy', outage_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Outage type', new_outage_type_path %>

app/views/outage_types/new.html.erb
<h1>New outage_type</h1>

<%= render 'form' %>

<%= link_to 'Back', outage_types_path %>

app/views/outage_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @outage_type.name %>
</p>

<p>
  <b>Code:</b>
  <%= @outage_type.code %>
</p>

<p>
  <b>Description:</b>
  <%= @outage_type.description %>
</p>

<p>
  <b>Active:</b>
  <%= @outage_type.active %>
</p>

<p>
  <b>Created by:</b>
  <%= @outage_type.created_by %>
</p>


<%= link_to 'Edit', edit_outage_type_path(@outage_type) %> |
<%= link_to 'Back', outage_types_path %>