config/routes.rb
SystemStatus::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :outage_types

  resources :status_reports

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  root to: 'static_pages#home'

end

app/models/status_report.rb
class StatusReport < ActiveRecord::Base
belongs_to :outage_type


validates :name, :start_time, :affected_groups, :affected_services, :description, :created_by, :presence => true

validates :start_time, :end_time, :numericality => {:only_integer => true, :less_than => 2400}
end

app/controllers/status_reports_controller.rb
class StatusReportsController < ApplicationController
  # GET /status_reports
  # GET /status_reports.json
  def index
    @status_reports = StatusReport.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @status_reports }
    end
  end

  # GET /status_reports/1
  # GET /status_reports/1.json
  def show
    @status_report = StatusReport.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @status_report }
    end
  end

  # GET /status_reports/new
  # GET /status_reports/new.json
  def new
    @status_report = StatusReport.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @status_report }
    end
  end

  # GET /status_reports/1/edit
  def edit
    @status_report = StatusReport.find(params[:id])
  end

  # POST /status_reports
  # POST /status_reports.json
  def create
    @status_report = StatusReport.new(params[:status_report])

    respond_to do |format|
      if @status_report.save
        format.html { redirect_to @status_report, :notice => 'Status report was successfully created.' }
        format.json { render :json => @status_report, :status => :created, :location => @status_report }
      else
        format.html { render :action => "new" }
        format.json { render :json => @status_report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /status_reports/1
  # PUT /status_reports/1.json
  def update
    @status_report = StatusReport.find(params[:id])

    respond_to do |format|
      if @status_report.update_attributes(params[:status_report])
        format.html { redirect_to @status_report, :notice => 'Status report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @status_report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /status_reports/1
  # DELETE /status_reports/1.json
  def destroy
    @status_report = StatusReport.find(params[:id])
    @status_report.destroy

    respond_to do |format|
      format.html { redirect_to status_reports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/status_reports_helper.rb
module StatusReportsHelper
end

app/views/status_reports/_form.html.erb
<%= form_for(@status_report) do |f| %>
  <% if @status_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status_report.errors.count, "error") %> prohibited this status_report from being saved:</h2>

      <ul>
      <% @status_report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

<div class="field">
	    <%= f.label :outage_type_id %><br />
	    <%= f.select :outage_type_id, OutageType.all.collect {|p| [p.name, p.id] }, :prompt => 'Select an outage type' %>

</div>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.number_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.number_field :end_time %>
  </div>
  <div class="field">
    <%= f.label :affected_groups %><br />
    <%= f.text_field :affected_groups %>
  </div>
  <div class="field">
    <%= f.label :affected_services %><br />
    <%= f.text_field :affected_services %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :scheduled %><br />
    <%= f.check_box :scheduled %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br />
	  <%= f.select :created_by, User.all.collect {|p| [p.name, p.id] }, :prompt => 'Select a user' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/status_reports/edit.html.erb
<h1>Editing status_report</h1>

<%= render 'form' %>

<%= link_to 'Show', @status_report %> |
<%= link_to 'Back', status_reports_path %>

app/views/status_reports/index.html.erb
<h1>Listing status_reports</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Outage type</th>
    <th>Date</th>
    <th>Start time</th>
    <th>End time</th>
    <th>Affected groups</th>
    <th>Affected services</th>
    <th>Description</th>
    <th>Scheduled</th>
    <th>Active</th>
    <th>Created by</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @status_reports.each do |status_report| %>
  <tr>
    <td><%= status_report.name %></td>
    <td><%= status_report.outage_type_id %></td>
    <td><%= status_report.date %></td>
    <td><%= status_report.start_time %></td>
    <td><%= status_report.end_time %></td>
    <td><%= status_report.affected_groups %></td>
    <td><%= status_report.affected_services %></td>
    <td><%= status_report.description %></td>
    <td><%= status_report.scheduled %></td>
    <td><%= status_report.active %></td>
    <td><%= status_report.created_by %></td>
    <td><%= status_report.created_at %></td>
    <td><%= status_report.updated_at %></td>
    <td><%= link_to 'Show', status_report %></td>
    <td><%= link_to 'Edit', edit_status_report_path(status_report) %></td>
    <td><%= link_to 'Destroy', status_report, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Status report', new_status_report_path %>

app/views/status_reports/new.html.erb
<h1>New status_report</h1>

<%= render 'form' %>

<%= link_to 'Back', status_reports_path %>

app/views/status_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @status_report.name %>
</p>

<p>
  <b>Outage type:</b>
  <%= @status_report.outage_type_id %>
</p>

<p>
  <b>Date:</b>
  <%= @status_report.date %>
</p>

<p>
  <b>Start time:</b>
  <%= @status_report.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @status_report.end_time %>
</p>

<p>
  <b>Affected groups:</b>
  <%= @status_report.affected_groups %>
</p>

<p>
  <b>Affected services:</b>
  <%= @status_report.affected_services %>
</p>

<p>
  <b>Description:</b>
  <%= @status_report.description %>
</p>

<p>
  <b>Scheduled:</b>
  <%= @status_report.scheduled %>
</p>

<p>
  <b>Active:</b>
  <%= @status_report.active %>
</p>

<p>
  <b>Created by:</b>
  <%= User.find(@status_report.created_by).name %>
</p>

<p>
  <b>Created at:</b>
  <%= @status_report.created_at %>
</p>

<p>
  <b>Updated at:</b>
  <%= @status_report.updated_at %>
</p>


<%= link_to 'Edit', edit_status_report_path(@status_report) %> |
<%= link_to 'Back', status_reports_path %>